-- Neura Chat — complete database setup
--
-- Generated by concatenating supabase/migrations/*.sql in filename order.
-- Paste this whole file into the Supabase SQL editor and press Run.
--
-- Safe to run more than once: tables use "if not exists", functions use
-- "create or replace", and every policy is dropped before being recreated,
-- so a partial earlier run does not block this.
--
-- Source of truth remains the individual files in supabase/migrations/.
-- Regenerate with: node scripts/build-setup-sql.mjs


-- ========================================================================
-- 20260818120000_schema.sql
-- ========================================================================

-- Neura Chat foundation schema
-- Multi-tenant WhatsApp automation SaaS: organizations, WABA connections,
-- contacts/conversations/messages, templates, campaigns, automations.

create extension if not exists pgcrypto with schema extensions;

-- =========================================================================
-- organizations
-- =========================================================================
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

-- =========================================================================
-- org_members — links auth.users to organizations with a role
-- =========================================================================
create table if not exists public.org_members (
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  created_at timestamptz not null default now(),
  primary key (org_id, user_id)
);

create index if not exists org_members_user_id_idx on public.org_members(user_id);

-- =========================================================================
-- waba_connections — one row per WhatsApp Business Account / phone number
-- connected to an org via the Meta Cloud API.
-- =========================================================================
create table if not exists public.waba_connections (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  waba_id text not null,
  phone_number_id text not null,
  meta_app_id text not null,
  access_token_encrypted text not null,
  webhook_verify_token text not null,
  status text not null default 'pending' check (status in ('pending', 'active', 'disabled', 'error')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- phone_number_id is how inbound webhooks are routed back to an org, and
-- webhook_verify_token is how the GET verification handshake finds the
-- right connection — both must be globally unique.
create unique index if not exists waba_connections_phone_number_id_key on public.waba_connections(phone_number_id);
create unique index if not exists waba_connections_webhook_verify_token_key on public.waba_connections(webhook_verify_token);
create index if not exists waba_connections_org_id_idx on public.waba_connections(org_id);

-- =========================================================================
-- contacts
-- =========================================================================
create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  wa_id text not null,
  name text,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, wa_id)
);

create index if not exists contacts_org_id_idx on public.contacts(org_id);
create index if not exists contacts_tags_idx on public.contacts using gin (tags);

-- =========================================================================
-- conversations — one running thread per contact
-- =========================================================================
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  contact_id uuid not null references public.contacts(id) on delete cascade,
  last_message_at timestamptz,
  status text not null default 'open' check (status in ('open', 'pending', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  unique (org_id, contact_id)
);

create index if not exists conversations_org_id_idx on public.conversations(org_id);
create index if not exists conversations_last_message_at_idx on public.conversations(org_id, last_message_at desc);

-- =========================================================================
-- messages
-- org_id is denormalized from conversations (see trigger below) purely so
-- RLS policies can check it directly without a join on every row.
-- =========================================================================
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  direction text not null check (direction in ('inbound', 'outbound')),
  type text not null,
  content jsonb not null default '{}'::jsonb,
  wa_message_id text,
  status text not null default 'sent' check (status in ('sent', 'delivered', 'read', 'failed')),
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_id_idx on public.messages(conversation_id, created_at);
create index if not exists messages_org_id_idx on public.messages(org_id);
create unique index if not exists messages_wa_message_id_key on public.messages(wa_message_id) where wa_message_id is not null;

-- Keep messages.org_id in sync with its conversation, regardless of what a
-- client supplies, so the RLS check below can never be bypassed by sending
-- a mismatched org_id.
create or replace function public.set_message_org_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select org_id into new.org_id from public.conversations where id = new.conversation_id;
  if new.org_id is null then
    raise exception 'conversation % does not exist', new.conversation_id;
  end if;
  return new;
end;
$$;

drop trigger if exists messages_set_org_id on public.messages;
create trigger messages_set_org_id
  before insert or update of conversation_id on public.messages
  for each row execute function public.set_message_org_id();

-- =========================================================================
-- message_templates — mirrors Meta's WhatsApp template model
-- =========================================================================
create table if not exists public.message_templates (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  category text not null default 'UTILITY' check (category in ('MARKETING', 'UTILITY', 'AUTHENTICATION')),
  status text not null default 'draft' check (status in ('draft', 'pending', 'approved', 'rejected', 'disabled')),
  language text not null default 'en_US',
  components_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, name, language)
);

create index if not exists message_templates_org_id_idx on public.message_templates(org_id);

-- =========================================================================
-- campaigns
-- =========================================================================
create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  template_id uuid references public.message_templates(id) on delete set null,
  segment_filter jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'running', 'completed', 'cancelled', 'failed')),
  scheduled_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists campaigns_org_id_idx on public.campaigns(org_id);

-- =========================================================================
-- campaign_recipients
-- org_id is denormalized from campaigns for the same reason as messages.
-- =========================================================================
create table if not exists public.campaign_recipients (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  contact_id uuid not null references public.contacts(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'sent', 'delivered', 'read', 'failed')),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (campaign_id, contact_id)
);

create index if not exists campaign_recipients_campaign_id_idx on public.campaign_recipients(campaign_id);
create index if not exists campaign_recipients_org_id_idx on public.campaign_recipients(org_id);

create or replace function public.set_campaign_recipient_org_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select org_id into new.org_id from public.campaigns where id = new.campaign_id;
  if new.org_id is null then
    raise exception 'campaign % does not exist', new.campaign_id;
  end if;
  return new;
end;
$$;

drop trigger if exists campaign_recipients_set_org_id on public.campaign_recipients;
create trigger campaign_recipients_set_org_id
  before insert or update of campaign_id on public.campaign_recipients
  for each row execute function public.set_campaign_recipient_org_id();

-- =========================================================================
-- automation_flows
-- =========================================================================
create table if not exists public.automation_flows (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  trigger_type text not null,
  trigger_config jsonb not null default '{}'::jsonb,
  actions_json jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists automation_flows_org_id_idx on public.automation_flows(org_id);

-- ========================================================================
-- 20260818120100_rls_policies.sql
-- ========================================================================

-- RLS for every Neura Chat table, scoped by org membership.
--
-- Baseline rule (as specified): a user may read/write a row only if its
-- org_id belongs to an org they are a member of (org_members).
--
-- Two deliberate exceptions to that baseline, called out explicitly for
-- review:
--   * org_members  — write access (insert/update/delete) is restricted to
--     org owners/admins. Under the plain "any member" rule, any member
--     could grant themselves or an arbitrary user_id the 'owner' role in
--     their own org (privilege escalation), or remove other members.
--     Read access still follows the plain rule. Members may still delete
--     their own membership row (leave the org).
--   * waba_connections — write access is restricted to owners/admins,
--     since this table holds encrypted Meta access tokens and the webhook
--     verify token. Read access still follows the plain rule (any member
--     can see connection status).
-- Every other table (contacts, conversations, messages, message_templates,
-- campaigns, campaign_recipients, automation_flows) uses the plain rule
-- uniformly for select/insert/update/delete.

-- =========================================================================
-- Helper functions (security definer to avoid RLS recursion on org_members)
-- =========================================================================
create or replace function public.is_org_member(p_org_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.org_members m
    where m.org_id = p_org_id and m.user_id = auth.uid()
  );
$$;

create or replace function public.is_org_admin(p_org_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.org_members m
    where m.org_id = p_org_id and m.user_id = auth.uid() and m.role in ('owner', 'admin')
  );
$$;

grant execute on function public.is_org_member(uuid) to authenticated;
grant execute on function public.is_org_admin(uuid) to authenticated;

-- =========================================================================
-- organizations
-- =========================================================================
alter table public.organizations enable row level security;

drop policy if exists organizations_select on public.organizations;
create policy organizations_select on public.organizations
  for select to authenticated
  using (public.is_org_member(id));

drop policy if exists organizations_update on public.organizations;
create policy organizations_update on public.organizations
  for update to authenticated
  using (public.is_org_admin(id))
  with check (public.is_org_admin(id));

-- No insert/delete policy for the authenticated role: orgs are created by
-- the handle_new_user trigger (security definer, runs as table owner and
-- bypasses RLS) and are not deletable from the app in this stage.

-- =========================================================================
-- org_members
-- =========================================================================
alter table public.org_members enable row level security;

drop policy if exists org_members_select on public.org_members;
create policy org_members_select on public.org_members
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists org_members_insert on public.org_members;
create policy org_members_insert on public.org_members
  for insert to authenticated
  with check (public.is_org_admin(org_id));

drop policy if exists org_members_update on public.org_members;
create policy org_members_update on public.org_members
  for update to authenticated
  using (public.is_org_admin(org_id))
  with check (public.is_org_admin(org_id));

drop policy if exists org_members_delete_admin on public.org_members;
create policy org_members_delete_admin on public.org_members
  for delete to authenticated
  using (public.is_org_admin(org_id));

drop policy if exists org_members_delete_self on public.org_members;
create policy org_members_delete_self on public.org_members
  for delete to authenticated
  using (user_id = auth.uid());

-- =========================================================================
-- waba_connections
-- =========================================================================
alter table public.waba_connections enable row level security;

drop policy if exists waba_connections_select on public.waba_connections;
create policy waba_connections_select on public.waba_connections
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists waba_connections_insert on public.waba_connections;
create policy waba_connections_insert on public.waba_connections
  for insert to authenticated
  with check (public.is_org_admin(org_id));

drop policy if exists waba_connections_update on public.waba_connections;
create policy waba_connections_update on public.waba_connections
  for update to authenticated
  using (public.is_org_admin(org_id))
  with check (public.is_org_admin(org_id));

drop policy if exists waba_connections_delete on public.waba_connections;
create policy waba_connections_delete on public.waba_connections
  for delete to authenticated
  using (public.is_org_admin(org_id));

-- =========================================================================
-- contacts
-- =========================================================================
alter table public.contacts enable row level security;

drop policy if exists contacts_select on public.contacts;
create policy contacts_select on public.contacts
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists contacts_insert on public.contacts;
create policy contacts_insert on public.contacts
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists contacts_update on public.contacts;
create policy contacts_update on public.contacts
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists contacts_delete on public.contacts;
create policy contacts_delete on public.contacts
  for delete to authenticated
  using (public.is_org_member(org_id));

-- =========================================================================
-- conversations
-- =========================================================================
alter table public.conversations enable row level security;

drop policy if exists conversations_select on public.conversations;
create policy conversations_select on public.conversations
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists conversations_insert on public.conversations;
create policy conversations_insert on public.conversations
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists conversations_update on public.conversations;
create policy conversations_update on public.conversations
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists conversations_delete on public.conversations;
create policy conversations_delete on public.conversations
  for delete to authenticated
  using (public.is_org_member(org_id));

-- =========================================================================
-- messages
-- =========================================================================
alter table public.messages enable row level security;

drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists messages_update on public.messages;
create policy messages_update on public.messages
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists messages_delete on public.messages;
create policy messages_delete on public.messages
  for delete to authenticated
  using (public.is_org_member(org_id));

-- =========================================================================
-- message_templates
-- =========================================================================
alter table public.message_templates enable row level security;

drop policy if exists message_templates_select on public.message_templates;
create policy message_templates_select on public.message_templates
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists message_templates_insert on public.message_templates;
create policy message_templates_insert on public.message_templates
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists message_templates_update on public.message_templates;
create policy message_templates_update on public.message_templates
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists message_templates_delete on public.message_templates;
create policy message_templates_delete on public.message_templates
  for delete to authenticated
  using (public.is_org_member(org_id));

-- =========================================================================
-- campaigns
-- =========================================================================
alter table public.campaigns enable row level security;

drop policy if exists campaigns_select on public.campaigns;
create policy campaigns_select on public.campaigns
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists campaigns_insert on public.campaigns;
create policy campaigns_insert on public.campaigns
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists campaigns_update on public.campaigns;
create policy campaigns_update on public.campaigns
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists campaigns_delete on public.campaigns;
create policy campaigns_delete on public.campaigns
  for delete to authenticated
  using (public.is_org_member(org_id));

-- =========================================================================
-- campaign_recipients
-- =========================================================================
alter table public.campaign_recipients enable row level security;

drop policy if exists campaign_recipients_select on public.campaign_recipients;
create policy campaign_recipients_select on public.campaign_recipients
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists campaign_recipients_insert on public.campaign_recipients;
create policy campaign_recipients_insert on public.campaign_recipients
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists campaign_recipients_update on public.campaign_recipients;
create policy campaign_recipients_update on public.campaign_recipients
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists campaign_recipients_delete on public.campaign_recipients;
create policy campaign_recipients_delete on public.campaign_recipients
  for delete to authenticated
  using (public.is_org_member(org_id));

-- =========================================================================
-- automation_flows
-- =========================================================================
alter table public.automation_flows enable row level security;

drop policy if exists automation_flows_select on public.automation_flows;
create policy automation_flows_select on public.automation_flows
  for select to authenticated
  using (public.is_org_member(org_id));

drop policy if exists automation_flows_insert on public.automation_flows;
create policy automation_flows_insert on public.automation_flows
  for insert to authenticated
  with check (public.is_org_member(org_id));

drop policy if exists automation_flows_update on public.automation_flows;
create policy automation_flows_update on public.automation_flows
  for update to authenticated
  using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists automation_flows_delete on public.automation_flows;
create policy automation_flows_delete on public.automation_flows
  for delete to authenticated
  using (public.is_org_member(org_id));

-- ========================================================================
-- 20260818120200_auth_signup_trigger.sql
-- ========================================================================

-- On every new auth.users row (email/password or Google OAuth), create an
-- organization and make the new user its owner. The trigger runs inside
-- the same transaction as the auth.users insert, so both writes are
-- atomic with account creation — if either insert fails, the user is
-- never created either.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_org_id uuid;
  org_name text;
begin
  org_name := coalesce(
    new.raw_user_meta_data ->> 'org_name',
    new.raw_user_meta_data ->> 'full_name',
    split_part(new.email, '@', 1),
    'My Organization'
  );

  insert into public.organizations (name)
  values (org_name)
  returning id into new_org_id;

  insert into public.org_members (org_id, user_id, role)
  values (new_org_id, new.id, 'owner');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ========================================================================
-- 20260820100000_admin_billing.sql
-- ========================================================================

-- Platform administration and billing layer.
--
-- Everything above this migration is tenant-scoped: a user reaches rows only
-- through org_members. This layer adds a second, orthogonal axis — platform
-- staff who operate the service itself and can see across every tenant.
-- That privilege is granted by a row in platform_admins and nothing else.

-- =========================================================================
-- platform_admins
-- =========================================================================
create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- security definer so policies can call it without recursing through
-- platform_admins' own RLS.
create or replace function public.is_platform_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.platform_admins a where a.user_id = auth.uid()
  );
$$;

grant execute on function public.is_platform_admin() to authenticated;

alter table public.platform_admins enable row level security;

-- Readable so the app can decide whether to show the admin nav. Deliberately
-- no insert/update/delete policy for `authenticated`: promoting a platform
-- admin is done out-of-band (SQL editor / service role), never from the app,
-- so an admin account cannot be created by anything the browser can reach.
drop policy if exists platform_admins_select on public.platform_admins;
create policy platform_admins_select on public.platform_admins
  for select to authenticated
  using (user_id = auth.uid() or public.is_platform_admin());

-- =========================================================================
-- plans — subscription catalogue
-- =========================================================================
create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  price_cents integer not null default 0 check (price_cents >= 0),
  currency text not null default 'INR',
  billing_interval text not null default 'monthly' check (billing_interval in ('monthly', 'yearly')),
  message_limit integer,
  contact_limit integer,
  seat_limit integer,
  features jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.plans enable row level security;

-- The catalogue is public to signed-in users (pricing page, upgrade flow);
-- only platform staff can change it.
drop policy if exists plans_select on public.plans;
create policy plans_select on public.plans
  for select to authenticated using (true);
drop policy if exists plans_insert on public.plans;
create policy plans_insert on public.plans
  for insert to authenticated with check (public.is_platform_admin());
drop policy if exists plans_update on public.plans;
create policy plans_update on public.plans
  for update to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists plans_delete on public.plans;
create policy plans_delete on public.plans
  for delete to authenticated using (public.is_platform_admin());

-- =========================================================================
-- add_ons — optional paid extras
-- =========================================================================
create table if not exists public.add_ons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  price_cents integer not null default 0 check (price_cents >= 0),
  currency text not null default 'INR',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.add_ons enable row level security;

drop policy if exists add_ons_select on public.add_ons;
create policy add_ons_select on public.add_ons
  for select to authenticated using (true);
drop policy if exists add_ons_insert on public.add_ons;
create policy add_ons_insert on public.add_ons
  for insert to authenticated with check (public.is_platform_admin());
drop policy if exists add_ons_update on public.add_ons;
create policy add_ons_update on public.add_ons
  for update to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists add_ons_delete on public.add_ons;
create policy add_ons_delete on public.add_ons
  for delete to authenticated using (public.is_platform_admin());

-- =========================================================================
-- subscriptions — one active plan per org
-- =========================================================================
create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null unique references public.organizations(id) on delete cascade,
  plan_id uuid references public.plans(id) on delete set null,
  status text not null default 'trialing' check (status in ('trialing', 'active', 'past_due', 'cancelled', 'expired')),
  current_period_start timestamptz not null default now(),
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_plan_id_idx on public.subscriptions(plan_id);

alter table public.subscriptions enable row level security;

-- Members see their own org's subscription; only platform staff mutate it,
-- so a tenant cannot promote itself onto a higher plan.
drop policy if exists subscriptions_select on public.subscriptions;
create policy subscriptions_select on public.subscriptions
  for select to authenticated
  using (public.is_org_member(org_id) or public.is_platform_admin());
drop policy if exists subscriptions_insert on public.subscriptions;
create policy subscriptions_insert on public.subscriptions
  for insert to authenticated with check (public.is_platform_admin());
drop policy if exists subscriptions_update on public.subscriptions;
create policy subscriptions_update on public.subscriptions
  for update to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists subscriptions_delete on public.subscriptions;
create policy subscriptions_delete on public.subscriptions
  for delete to authenticated using (public.is_platform_admin());

-- =========================================================================
-- org_add_ons
-- =========================================================================
create table if not exists public.org_add_ons (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  add_on_id uuid not null references public.add_ons(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (org_id, add_on_id)
);

create index if not exists org_add_ons_org_id_idx on public.org_add_ons(org_id);

alter table public.org_add_ons enable row level security;

drop policy if exists org_add_ons_select on public.org_add_ons;
create policy org_add_ons_select on public.org_add_ons
  for select to authenticated
  using (public.is_org_member(org_id) or public.is_platform_admin());
drop policy if exists org_add_ons_insert on public.org_add_ons;
create policy org_add_ons_insert on public.org_add_ons
  for insert to authenticated with check (public.is_platform_admin());
drop policy if exists org_add_ons_update on public.org_add_ons;
create policy org_add_ons_update on public.org_add_ons
  for update to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists org_add_ons_delete on public.org_add_ons;
create policy org_add_ons_delete on public.org_add_ons
  for delete to authenticated using (public.is_platform_admin());

-- =========================================================================
-- coupons
-- =========================================================================
create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_type text not null default 'percent' check (discount_type in ('percent', 'fixed')),
  discount_value integer not null check (discount_value > 0),
  max_redemptions integer,
  times_redeemed integer not null default 0,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.coupons enable row level security;

-- Not readable by tenants at all: listing coupons would let any signed-in
-- user enumerate every discount code. Redemption is validated server-side.
drop policy if exists coupons_all on public.coupons;
create policy coupons_all on public.coupons
  for all to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());

-- =========================================================================
-- orders — payment records, including onboarding fees
-- =========================================================================
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  plan_id uuid references public.plans(id) on delete set null,
  coupon_id uuid references public.coupons(id) on delete set null,
  kind text not null default 'subscription' check (kind in ('subscription', 'onboarding_fee', 'add_on', 'other')),
  description text,
  amount_cents integer not null default 0,
  currency text not null default 'INR',
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded')),
  provider text,
  provider_reference text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists orders_org_id_idx on public.orders(org_id, created_at desc);

alter table public.orders enable row level security;

drop policy if exists orders_select on public.orders;
create policy orders_select on public.orders
  for select to authenticated
  using (public.is_org_member(org_id) or public.is_platform_admin());
drop policy if exists orders_insert on public.orders;
create policy orders_insert on public.orders
  for insert to authenticated with check (public.is_platform_admin());
drop policy if exists orders_update on public.orders;
create policy orders_update on public.orders
  for update to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists orders_delete on public.orders;
create policy orders_delete on public.orders
  for delete to authenticated using (public.is_platform_admin());

-- =========================================================================
-- support_tickets
-- =========================================================================
create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  subject text not null,
  body text not null,
  status text not null default 'open' check (status in ('open', 'pending', 'resolved', 'closed')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_org_id_idx on public.support_tickets(org_id, created_at desc);
create index if not exists support_tickets_status_idx on public.support_tickets(status);

alter table public.support_tickets enable row level security;

drop policy if exists support_tickets_select on public.support_tickets;
create policy support_tickets_select on public.support_tickets
  for select to authenticated
  using (public.is_org_member(org_id) or public.is_platform_admin());
-- Tenants raise their own tickets…
drop policy if exists support_tickets_insert on public.support_tickets;
create policy support_tickets_insert on public.support_tickets
  for insert to authenticated
  with check (public.is_org_member(org_id));
-- …but only staff change status or priority.
drop policy if exists support_tickets_update on public.support_tickets;
create policy support_tickets_update on public.support_tickets
  for update to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists support_tickets_delete on public.support_tickets;
create policy support_tickets_delete on public.support_tickets
  for delete to authenticated using (public.is_platform_admin());

create table if not exists public.support_ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  author_id uuid references auth.users(id) on delete set null,
  body text not null,
  is_staff boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists support_ticket_messages_ticket_idx on public.support_ticket_messages(ticket_id, created_at);

-- Same denormalisation trick as messages: copy org_id from the parent ticket
-- so RLS checks it without a join, and overwrite whatever the client sent.
create or replace function public.set_ticket_message_org_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select org_id into new.org_id from public.support_tickets where id = new.ticket_id;
  if new.org_id is null then
    raise exception 'support ticket % does not exist', new.ticket_id;
  end if;
  return new;
end;
$$;

drop trigger if exists support_ticket_messages_set_org_id on public.support_ticket_messages;
create trigger support_ticket_messages_set_org_id
  before insert or update of ticket_id on public.support_ticket_messages
  for each row execute function public.set_ticket_message_org_id();

alter table public.support_ticket_messages enable row level security;

drop policy if exists support_ticket_messages_select on public.support_ticket_messages;
create policy support_ticket_messages_select on public.support_ticket_messages
  for select to authenticated
  using (public.is_org_member(org_id) or public.is_platform_admin());
drop policy if exists support_ticket_messages_insert on public.support_ticket_messages;
create policy support_ticket_messages_insert on public.support_ticket_messages
  for insert to authenticated
  with check (public.is_org_member(org_id) or public.is_platform_admin());
drop policy if exists support_ticket_messages_delete on public.support_ticket_messages;
create policy support_ticket_messages_delete on public.support_ticket_messages
  for delete to authenticated using (public.is_platform_admin());

-- =========================================================================
-- webhook_logs — inbound Meta deliveries, for debugging
-- =========================================================================
create table if not exists public.webhook_logs (
  id uuid primary key default gen_random_uuid(),
  org_id uuid references public.organizations(id) on delete cascade,
  phone_number_id text,
  event_type text,
  signature_valid boolean not null default false,
  payload jsonb,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists webhook_logs_created_at_idx on public.webhook_logs(created_at desc);
create index if not exists webhook_logs_org_id_idx on public.webhook_logs(org_id, created_at desc);

alter table public.webhook_logs enable row level security;

-- Rows with a null org_id are deliveries we could not attribute to a tenant
-- (unknown phone_number_id, bad signature) — staff-only by construction.
drop policy if exists webhook_logs_select on public.webhook_logs;
create policy webhook_logs_select on public.webhook_logs
  for select to authenticated
  using ((org_id is not null and public.is_org_member(org_id)) or public.is_platform_admin());
drop policy if exists webhook_logs_delete on public.webhook_logs;
create policy webhook_logs_delete on public.webhook_logs
  for delete to authenticated using (public.is_platform_admin());
-- No insert policy: only the webhook route writes here, via the service role.

-- =========================================================================
-- platform_settings — global key/value config
-- =========================================================================
create table if not exists public.platform_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  description text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

alter table public.platform_settings enable row level security;

drop policy if exists platform_settings_all on public.platform_settings;
create policy platform_settings_all on public.platform_settings
  for all to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());

-- =========================================================================
-- Seed the plan catalogue so the billing screens aren't empty on first run.
-- =========================================================================
insert into public.plans (name, slug, description, price_cents, billing_interval, message_limit, contact_limit, seat_limit, features, sort_order)
values
  ('Starter', 'starter', 'For teams getting started on WhatsApp', 99900, 'monthly', 1000, 500, 2,
   '["1,000 messages/mo","500 contacts","2 team seats","1 WhatsApp number"]'::jsonb, 1),
  ('Growth', 'growth', 'For growing teams running campaigns', 299900, 'monthly', 10000, 5000, 10,
   '["10,000 messages/mo","5,000 contacts","10 team seats","Campaigns & automations"]'::jsonb, 2),
  ('Scale', 'scale', 'High volume, multiple numbers', 799900, 'monthly', 100000, 50000, 50,
   '["100,000 messages/mo","50,000 contacts","50 team seats","Priority support"]'::jsonb, 3)
on conflict (slug) do nothing;

insert into public.add_ons (name, slug, description, price_cents)
values
  ('Extra WhatsApp number', 'extra-number', 'Connect an additional phone number', 49900),
  ('Onboarding & setup', 'onboarding', 'Guided Meta Cloud API setup', 999900),
  ('Priority support', 'priority-support', '4-hour response SLA', 199900)
on conflict (slug) do nothing;

insert into public.platform_settings (key, value, description)
values
  ('branding', '{"product_name":"Neura Chat","support_email":"support@neuraxine.com"}'::jsonb, 'Product name and support contact'),
  ('signups', '{"enabled":true,"require_onboarding_fee":false}'::jsonb, 'Control new tenant signups')
on conflict (key) do nothing;
